### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by grossix** [FuzzyHobbit/bustabit-webserver#15]
@npm start
Listening on port  3841
[INTERNAL_ERROR]  ReferenceError: Promise is not defined
    at Object.exports.promise (/var/www/html/crash/node_modules/recaptcha-validator/index.js:23:14)
    at Object.exports.callback (/var/www/html/crash/node_modules/recaptcha-validator/index.js:79:11)
    at Object.recaptchaRestrict [as handle] (/var/www/html/crash/server/routes.js:92:22)
    at next_layer (/var/www/html/crash/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/var/www/html/crash/node_modules/express/lib/router/route.js:107:5)
    at c (/var/www/html/crash/node_modules/express/lib/router/index.js:195:24)
    at Function.proto.process_params (/var/www/html/crash/node_modules/express/lib/router/index.js:253:12)
    at next (/var/www/html/crash/node_modules/express/lib/router/index.js:189:19)
    at next (/var/www/html/crash/node_modules/express/lib/router/index.js:166:38)
    at next (/var/www/html/crash/node_modules/express/lib/router/index.js:166:38)

Why? :/

**Comment by shamimiceewu025** [comment]
use command "node server.js"
it resolve the error

**Comment by grossix** [comment]
Seems like I can start the server now but get the following error:
[INTERNAL_ERROR] Unable to get site stats:
error: password authentication failed for user "root"

I cannot find the right configuration file for this, where do i enter the password for "root"?

And also, the problem with my recaptcha configuration, wheres the configurationfile for that?

**Comment by shamimiceewu025** [comment]
There is No Default User root. If you Create User admin as User then You need to login using admin. This error comes When You attempt Fail Login.

**Comment by grossix** [comment]
I understand, how about the captcha errors? How can i solve them?

**Comment by yangga** [comment]
anyone solved this problem??

**Comment by shamimiceewu025** [comment]
@yangga please describe your problem

**Comment by yangga** [comment]
@shamimiceewu025 In my case, after login with recaptcha things, then show up above exception error msg. It's also failed with new generated recaptcha keys.

always the exception was occured at "function recaptchaRestrict(req, res, next)" (/server/routes.js). I just added except code temporarily like this,
line #92,

------------------------------------------------------------------------------------------------
 function recaptchaRestrict(req, res, next) {
  var recaptcha = lib.removeNullsAndTrim(req.body['g-recaptcha-response']);
  if (!recaptcha) {
    return res.send('No recaptcha submitted, go back and try again');
  }

  next();
  return;
------------------------------------------------------------------------------------------------

I'm not sure this solution is nice...

**Comment by Lalitpatadiya12** [comment]
I am also having same issue,

ddos: starting params:  { maxcount: 30,
  burst: 5,
  limit: 20,
  maxexpiry: 120,
  checkinterval: 1,
  errormessage: 'Error',
  testmode: false,
  silent: false,
  silentStart: false,
  responseStatus: 429 }
Listening on port  3841
[INTERNAL_ERROR] Unable to get site stats:
Error: connect ECONNREFUSED 46.37.190.146:5432

Any one idea ..?

**Comment by shamimiceewu025** [comment]
5432 port use already. This port use for postgresql
