### ISSUE TITLE
Can someone install it instead?

### ISSUE THREAD

**Issue by shakwon1** [FuzzyHobbit/bustabit-webserver#18]
Good morning
I am Japanese
I want to develop bustabit
It's so hard to do it alone
Can someone install it instead?
My Skype is "shakwon1"
Show various versions
You can pay up to $ 1500 in amount.
Please help me

**Comment by alexk345** [comment]
@shakwon1 I can help after if i make it run. hahaha

I am stuck at depositor

bitnami@ip-172-26-8-162:/opt/bitnami/apps/depositor$ npm run-script  generate-wallet

> bv-notifier@0.0.1 generate-wallet /opt/bitnami/apps/depositor
> env $(cat .env | xargs) node ./src/generate_wallet > .wallet.sh

/opt/bitnami/apps/depositor/node_modules/bitcoinjs-lib/node_modules/base-x/index.js:47
    if (string.length === 0) return []
              ^

TypeError: Cannot read property 'length' of undefined
    at decodeUnsafe (/opt/bitnami/apps/depositor/node_modules/bitcoinjs-lib/node_modules/base-x/index.js:47:15)
    at Object.decode (/opt/bitnami/apps/depositor/node_modules/bitcoinjs-lib/node_modules/base-x/index.js:75:17)
    at Object.decode (/opt/bitnami/apps/depositor/node_modules/bitcoinjs-lib/node_modules/bs58check/index.js:45:22)
    at Function.HDNode.fromBase58 (/opt/bitnami/apps/depositor/node_modules/bitcoinjs-lib/src/hdnode.js:55:28)
    at Object.<anonymous> (/opt/bitnami/apps/depositor/src/generate_wallet.js:4:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bv-notifier@0.0.1 generate-wallet: `env $(cat .env | xargs) node ./src/generate_wallet > .wallet.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bv-notifier@0.0.1 generate-wallet script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
=================================================

Do i have to deposit 1bitcoin mak ethis game run? at present on play it says connecting

**Comment by shakwon1** [comment]
@alexk345 Is it possible for me to install it?
Can you print like a sample site?
http://bst24.co.kr/

**Comment by alexk345** [comment]
I am stuck. Game is not connecting yet.

**Comment by alexk345** [comment]
hi

I have not installed it .

thanks
alexk
surrey

**Comment by shamimiceewu025** [comment]
http://bst24.co.kr/ this site development complete by me . If anyone need just contact shamim.ice.ewu@gmail.com / skype: forhadshamim88@hotmail.com

**Comment by alexk345** [comment]
hi

I have three problem

1. After login it goes to home page
2. No block found in depositor
3. Bitcoind  stops connecting to rpcport 8332 after few min.

Other than this problem how does this stuff own. Let say you are owner how
do you deposit 1BTC? after login?

I just need some background on how this stuff work.I am programmer but new
to bit coin

I know korea from 2013. Before that i won't find korea if someone asked me.
Now i am kdrama expert. Are you programmer then we could develop website
later stage.

Better mydramalist.

thanks
alexk
surrey

**Comment by shamimiceewu025** [comment]
1: you need configure which page it goes after login. default is home page. that why it goes to home page.
2: bitcoin fullnode need download all blocks information. it need time.
3: your bitcoind may be crashed that why. it require 2GB RAM + 130 GB HDD (check configuration)

**Comment by alexk345** [comment]
hi

Hahaha. I think that is it. its 1GB Host.
Some asked me to install and i thought it woulld be breeze but no info
available.
How long bitcoin take to download? 3days?
Also is it designed to go to home page? because i am in play it still say i
have to login.

thanks
alexk

**Comment by shamimiceewu025** [comment]
depend on server config & bandwith. if server down then also stop download process. take avarage 2 to 7 days

**Comment by alexk345** [comment]
hi

How long you took from the beginning to finish?

thanks
alexk
surrey

**Comment by alexk345** [comment]
hi

Thnaks for your suggestion. I moved to 2Gb 40gb hard disk for now.

Bitcoind running 30 min now that seems to be working

Login basically don't login i am debugging the code. it worked before i
changed to production

thanks
alexk
surrey

**Comment by alexk345** [comment]
hi

is there a way to download blockchain faster than bitcoind? Because i may
have to move to different host later and don't want to download again.

Any ideas?

 337677 downloaded. how many total?

Does it start from 0 everytime i restart bitcoind?

I recompiled the code because game did n't show and that some how blocked
login? or may be it work after i downloaded all blockchain?

Where do u deposit 1 BTC for game to work?

I appreciate it.

thanks
alexk
surrey

**Comment by alexk345** [comment]
npm start - login work but game don't load
npm run start-dev with node_env=production shows game page and i even able
to bet but blocks is not downloaded fully.
I want to know correct way to run these server.

May be npm start work when i downloaded all blocks? how do we know its
done? any indication to test?

**Comment by shamimiceewu025** [comment]
@shakwon1 is a scammer. he stole my full script . But unable to run properly. Please no one help this kind of scammer. 

http://one222.com/ is use that stolen script.

**Comment by alexk345** [comment]
Is there alternative to bitcoind? How did he stole script and run it in a day. I am still struggling 3 days. Nothing works.

**Comment by shamimiceewu025** [comment]
They contact me & after install stole my script. That version is without bitcoin. That why they able to run. But unable to 100%working.

**Comment by alexk345** [comment]
why my bustabit don't work. game page (play) don't run (says connecting)
when i run npm start.
i got the script from some one. what it need to connect to game? I think i
am missing some configuration for connecting to game?
how yours run without bitcoind?

**Comment by shamimiceewu025** [comment]
Already inform that that copy was 100% modify. Knock me Skype I can help you to start. With bitcoin or without bitcoind.

**Comment by alexk345** [comment]
shamim , great job for fixing all my issues. Excellant work.

**Comment by donghyukhaha** [comment]
i have a trouble on installation Bustabit.. somebody help me

**Comment by shamimiceewu025** [comment]
please describe your problem & we are ready for help

**Comment by liomaria** [comment]
I upgraded the site. This is my website http://game.world00.com

**Comment by henrylight2014** [comment]
@shakwon1 
hello.
i can help you.
i can satisfy.
see https://bustabit.club.

**Comment by DrDraake** [comment]
Hey guys,

I am still trying to figure out this stuff after months of tinkering with it on and off.

I was able to get the gameserver, webserver, and depositer installed.... I think.

1) When I go to the page it has the link to play.  when I click on Play I get "Game Loading"  and in SSH I do not see any activity.  When I click play old theme I see "Connecting to server" and in SSH it says Client Joined 1 ~Guest~ Chat client error [join] Invalid channel name"

2) I can go to register and it prompts to fill in the info but has an error on the captcha.

3) When I click on login it shows the username and password field.

site:
http://mgtsglob.wwwls18.a2hosted.com/

Please any help would be awesome!!

Thank you.
DrDraake

**Comment by shamimiceewu025** [comment]
Follow 
https://github.com/FuzzyHobbit/bustabit-webserver/issues/10 
AND then remove your browser cache & then start.

Edit main.js

**Comment by DrDraake** [comment]
shamimiceewu025

I tried to follow the instructions in #10 but I think I messed it up.  I think it said to copy the files from the /webserver/node_modules/socket.io-client/dist folder to just the main socket.io-client folder?

What am I editing in the main.js folder??

**Comment by shamimiceewu025** [comment]
no. instead of copy file. just modify your main.js file
location of file : bustabit-webserver/client_new/scripts/main.js
change line 9 
socketio: '../../node_modules/socket.io-client/socket.io',
to
socketio: '../../node_modules/socket.io-client/dist/socket.io',

then clear your bowser cache & then try

**Comment by DrDraake** [comment]
Changed line 9 and now it has the 3 dots going in and out.
cleared the cashe, cookies, etc...

http://mgtsglob.wwwls18.a2hosted.com/

any other thoughts?

**Comment by DrDraake** [comment]
Do you use skype, discord, Line?

**Comment by shamimiceewu025** [comment]
forhad.shamim/forhadshamim88@hotmail.com  skype
your game server not running now. that why that error happned

**Comment by desirey** [comment]
Helle every body..
i need help install the bustabit.

I installed bustabit server 
configuration is below 
==========================
export GOROOT=/usr/local/go
export GOPATH=$GOROOT/bin
PATH=$PATH:$HOME/bin:$HOME/.local/bin:$GOPATH:/usr/local/go/bin/bin/:/usr/bin/:/usr/pgsql-9.6/bin/
export PATH
export DATABASE_URL=postgres://bustabit:xxxxxxxx@localhost/bustabitdb

export BIP32_DERIVED_KEY=xpub6AHA9hZDN11k2ijHMeS5QqHx2KP9aMBRhTDqANMnwVtdyw2TDYRmF8PjpvwUFcL1Et8Hj59S3gTSMcUQ5gAqTz3Wd8EsMTmF3DChhqPQBnU
export PORT=3841
==================
result is this
<<<<<< command result >>>>>>>>>
[bustabit@46 gameserver]$ npm start

> BustaBit@0.0.1 start /home/bustabit/gameserver
> node server.js --use_strict

DATABASE_URL:  postgres://bustabit:olf7KDKFS09@localhost/bustabitdb
Listening on port  3841  with http
Have a bankroll of:  1  btc





and install webserver also PORT number is 3841
( game server and webserver located same centos linux machine )
But result is blow
<<<<< webserver result >>>>>>>
[bustabit@46 webserver]$ npm start

> bustabit@2.0.0 start /home/bustabit/webserver
> node server/index
DATABASE_URL:  postgres://bustabit:xxxxxx@localhost/bustabitdb
booting CAB bustabit webserver
mode:DEBUG
ddos: starting params:  { maxcount: 30,
  burst: 5,
  limit: 20,
  maxexpiry: 120,
  checkinterval: 1,
  errormessage: 'Error',
  testmode: false,
  silent: false,
  silentStart: false,
  responseStatus: 429 }
chatServer)
Fri, 23 Feb 2018 18:16:04 GMT uncaughtException: listen EADDRINUSE :::3841
Error: listen EADDRINUSE :::3841
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Object.<anonymous> (/home/bustabit/webserver/server/index.js:248:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bustabit@2.0.0 start: `node server/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bustabit@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bustabit/.npm/_logs/2018-02-23T18_16_04_278Z-debug.log



I didn't know , what is my problem,
could you help me, or is there work for me, i will pay to you.
please help me ~~

my skype is is steven.tyler42

thank you.

**Comment by stevemill2014** [comment]
@desirey is scam.
this guy is japanese god them.

**Comment by justawesome11** [comment]
> Already inform that that copy was 100% modify. Knock me Skype I can help you to start. With bitcoin or without bitcoind.

bro can u help me setup bustabit for me,i will pay u bro.
