### ISSUE TITLE
i cant npm start webserver

### ISSUE THREAD

**Issue by benjang** [FuzzyHobbit/bustabit-webserver#24]
i cant npm start.... 

whats my problem?

my server os is ubuntu 14.04..

/root/bustabit-webserver/node_modules/pg/lib/index.js:16
const poolFactory = (Client) => {
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/bustabit-webserver/server/database.js:7:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by shamimiceewu025** [comment]
use command
node server/index.js

**Comment by benjang** [comment]
thanks shamimiceewu025
but still cant...

omg... very tired..ha..

/root/bustabit-webserver/node_modules/pg/lib/index.js:16
const poolFactory = (Client) => {
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/bustabit-webserver/server/database.js:7:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by shamimiceewu025** [comment]
run below 3 commands

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
