### ISSUE TITLE
how to install in windows!... plz help me

### ISSUE THREAD

**Issue by freettotto** [FuzzyHobbit/bustabit-webserver#44]
plz help me !! ToT

**Comment by freettotto** [comment]
$ npm start

> Bustabit@2.0.0 start C:\bustabit-webserver-master
> node server/index

DATABASE_URL:  postgres://localhost:5432/bustabitdb
(node:3280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Mon, 15 Oct 2018 22:46:04 GMT uncaughtException: listen EADDRINUSE :::3841
Error: listen EADDRINUSE :::3841
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Object.<anonymous> (C:\bustabit-webserver-master\server\index.js:217:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Bustabit@2.0.0 start: `node server/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Bustabit@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging outputabove.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aclmt\AppData\Roaming\npm-cache\_logs\2018-10-15T22_46_04_689Z-debug.log

**Comment by freettotto** [comment]
root@spooky-virtual-machine:/home/spooky/bustabit-webserver-master# psql -W -U bustabit -d bustabitdb -h localhost -f server/sql/schema.sql
Password for user bustabit: 
psql:server/sql/schema.sql:1: ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/plv8.control": No such file or directory
psql:server/sql/schema.sql:7: ERROR:  type "userclassenum" already exists
psql:server/sql/schema.sql:22: ERROR:  relation "users" already exists
psql:server/sql/schema.sql:25: ERROR:  multiple primary keys for table "users" are not allowed
psql:server/sql/schema.sql:27: ERROR:  relation "unique_username" already exists
psql:server/sql/schema.sql:28: ERROR:  relation "users_email_idx" already exists
psql:server/sql/schema.sql:29: ERROR:  relation "user_id_idx" already exists
psql:server/sql/schema.sql:36: ERROR:  relation "users_id_seq" already exists
ALTER SEQUENCE
ALTER TABLE
psql:server/sql/schema.sql:48: ERROR:  relation "blocks" already exists
psql:server/sql/schema.sql:51: ERROR:  multiple primary keys for table "blocks" are not allowed
psql:server/sql/schema.sql:68: ERROR:  relation "fundings" already exists
psql:server/sql/schema.sql:71: ERROR:  relation "fundings_user_id_bitcoin_deposit_txid_key" already exists
psql:server/sql/schema.sql:73: ERROR:  relation "fundings_user_id_idx" already exists
psql:server/sql/schema.sql:84: ERROR:  relation "games" already exists
psql:server/sql/schema.sql:86: ERROR:  multiple primary keys for table "games" are not allowed
psql:server/sql/schema.sql:93: ERROR:  relation "games_id_seq" already exists
ALTER SEQUENCE
ALTER TABLE
psql:server/sql/schema.sql:108: ERROR:  relation "giveaways" already exists
psql:server/sql/schema.sql:110: ERROR:  relation "giveaways_user_id_idx" already exists
psql:server/sql/schema.sql:117: ERROR:  relation "giveaways_id_seq" already exists
ALTER SEQUENCE
ALTER TABLE
psql:server/sql/schema.sql:123: ERROR:  constraint "giveaways_user_id_fkey" for relation "giveaways" already exists
psql:server/sql/schema.sql:138: ERROR:  relation "plays" already exists
psql:server/sql/schema.sql:140: ERROR:  multiple primary keys for table "plays" are not allowed
psql:server/sql/schema.sql:142: ERROR:  relation "plays_game_id_idx" already exists
psql:server/sql/schema.sql:144: ERROR:  relation "plays_user_id_idx" already exists
psql:server/sql/schema.sql:146: ERROR:  constraint "plays_game_id_fkey" for relation "plays" already exists
psql:server/sql/schema.sql:148: ERROR:  constraint "plays_user_id_fkey" for relation "plays" already exists
psql:server/sql/schema.sql:155: ERROR:  relation "plays_id_seq" already exists
ALTER SEQUENCE
ALTER TABLE
psql:server/sql/schema.sql:172: ERROR:  relation "recovery" already exists
psql:server/sql/schema.sql:173: ERROR:  relation "fki_foreing_user_id" already exists
psql:server/sql/schema.sql:189: ERROR:  relation "sessions" already exists
psql:server/sql/schema.sql:192: ERROR:  multiple primary keys for table "sessions" are not allowed
psql:server/sql/schema.sql:194: ERROR:  relation "sessions_user_id_idx" already exists
psql:server/sql/schema.sql:212: ERROR:  relation "users_view" already exists
psql:server/sql/schema.sql:221: ERROR:  relation "game_hashes" already exists
psql:server/sql/schema.sql:234: ERROR:  relation "leaderboard" already exists
psql:server/sql/schema.sql:239: ERROR:  relation "leaderboard_user_id_idx" already exists
psql:server/sql/schema.sql:241: ERROR:  relation "leaderboard_username_idx" already exists
psql:server/sql/schema.sql:243: ERROR:  relation "leaderboard_gross_profit_idx" already exists
psql:server/sql/schema.sql:245: ERROR:  relation "leaderboard_net_profit_idx" already exists
psql:server/sql/schema.sql:259: ERROR:  relation "chat_messages" already exists
psql:server/sql/schema.sql:261: ERROR:  relation "chat_messages_user_id_idx" already exists
psql:server/sql/schema.sql:262: ERROR:  relation "chat_messages_channel_id_idx" already exists
psql:server/sql/schema.sql:309: ERROR:  language "plv8" does not exist
psql:server/sql/schema.sql:313: ERROR:  function plays_users_stats_trigger() does not exist

**Comment by freettotto** [comment]
plz help me ToT

**Comment by id1385** [comment]
if u want install it on windows you must install plv8 extension for postgres
see : http://jasperfx.github.io/marten/documentation/admin/installing-plv8-windows/

**Comment by clementbalestrat** [comment]
@freettotto did you manage to fix your issue? I'm having the exact same problem.

**Comment by justawesome11** [comment]
jumkarry11@gmail.com
i can setup whole website for you in 10 mints with everything working like original bustabit.
i have my whole source ready,just let me know.

**Comment by cryptographic1337** [comment]
@freettotto  I can help you with your site if you would like. I got mine to work. Email me if you need help -> cryptographic1337@gmail.com
