### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by NoperDesign** [FuzzyHobbit/bustabit-webserver#50]
please help me!

```
root@Hurtworld:/var/www/html# npm start

> Bustabit@2.0.0 start /var/www/html
> node server/index

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/server/index.js:3:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 2.6.32-042stab134.8
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! Bustabit@2.0.0 start: `node server/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Bustabit@2.0.0 start script 'node server/index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Bustabit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Bustabit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Bustabit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log
```

**Comment by m-tech235** [comment]
npm audit fix --force

**Comment by tuckerritti** [comment]
did you run
`npm install`

**Comment by cryptographic1337** [comment]
@johany11 I can help you with your site if you would like. I got mine to work. Email me if you need help -> cryptographic1337@gmail.com

**Comment by cryptographic1337** [comment]
@NoperDesign I can help you with your site if you would like. I got mine to work. Email me if you need help -> cryptographic1337@gmail.com

**Comment by adminsync** [comment]
cryptographic is fraud and scammer,he will steal all ur btc.
warned in advance.
